name: Quartz_deb-build-testing
on:
  schedule:
    - cron: '36 8 * * *'
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: kentik/pkg@v1.0.0-rc8
        with:
          name: quartz
          version: 0.3
          arch: all
          format: deb
          package: quartz-spec.yaml
