name: Quartz_deb-build-testing
on: [push]
#  schedule:
#    - cron: '36 8 * * *'
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The branch is ${{ github.ref }} and the repo is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: kentik/pkg@v1.0.0-rc8
        with:
          name: quartz
          version: 0.3
          arch: x86_64
          format: deb
          package: package.yaml
